import type { AgentPresetConfig } from './agent-preset.config.js';
import { claudeAgentPresetConfig } from './claude-agent-preset.config.js';
import { codexAgentPresetConfig } from './codex-agent-preset.config.js';
import { cursorAgentPresetConfig } from './cursor-agent-preset.config.js';

/**
 * Centralized preset config registry.
 *
 * All production code should read agent paths and file names from this module
 * instead of inlining per-agent strings inside behaviors.
 *
 * Keep this as the single source of truth so sync behaviors stay fully generic.
 */
const presetConfigByAgent: Record<string, AgentPresetConfig> = {
  claude: claudeAgentPresetConfig,
  codex: codexAgentPresetConfig,
  cursor: cursorAgentPresetConfig,
};

/** Synthesizes an `AgentPresetConfig` from `agentName` when no built-in preset exists (custom agents). */
function buildFallbackPresetConfig(agentName: string): AgentPresetConfig {
  return {
    CONSTANTS: {
      AGENT_NAME: agentName,
      LOCAL_CONTENT_TARGET_ROOT: `.${agentName}`,
      MARKDOWN_CONTEXT_TARGET_FILE_NAME: `${agentName.toUpperCase()}.md`,
      MARKDOWN_SECTION_FILE: 'AGENTS.override.md',
      MARKDOWN_SECTION_HEADING: 'packages (generated by clankgsters)',
      MARKETPLACE_FILE: `.${agentName}/marketplace.json`,
      MARKETPLACE_SOURCE_FORMAT: 'prefixed',
      NATIVE_SKILLS_DIR: `.${agentName}/skills`,
      PLUGIN_MANIFEST_DIR: `.${agentName}-plugin`,
      RULES_MARKDOWN_FRONTMATTER: '---\nalwaysApply: true\n---\n\n',
      RULES_DIR: `.${agentName}/rules`,
      SETTINGS_FILE: `.${agentName}/settings.json`,
      get SETTINGS_MANIFEST_KEY() {
        return this.AGENT_NAME;
      },
      SKILLS_SYNC_ENABLED: false,
    },
  };
}

export const agentPresetConfigs = {
  /** Built-in presets keyed by agent name (`claude`, `codex`, `cursor`). */
  byAgent: presetConfigByAgent,
  /** Returns the preset for `agentName`, or a fallback from {@link buildFallbackPresetConfig} when unknown. */
  resolve(agentName: string): AgentPresetConfig {
    return presetConfigByAgent[agentName] ?? buildFallbackPresetConfig(agentName);
  },
};
