import type { AgentPresetConfig } from './agent-preset.config.js';

/** Codex preset constants as a single source of truth. */
export const codexAgentPresetConfig = {
  CONSTANTS: {
    AGENT_NAME: 'codex',
    GITIGNORE_COMMENT: '\n# clankgsters-sync: symlinked from CLANK.md for Codex\n',
    MARKDOWN_CONTEXT_TARGET_FILE_NAME: 'AGENTS.md',
    get GITIGNORE_ENTRY() {
      return this.MARKDOWN_CONTEXT_TARGET_FILE_NAME;
    },
    MARKDOWN_SECTION_FILE: 'AGENTS.override.md',
    MARKDOWN_SECTION_HEADING: 'packages (generated by clankgsters)',
    MARKETPLACE_FILE: '.codex/marketplace.json',
    MARKETPLACE_SOURCE_FORMAT: 'prefixed',
    NATIVE_SKILLS_DIR: '.codex/skills',
    PLUGIN_MANIFEST_DIR: '.codex-plugin',
    RULES_MARKDOWN_FRONTMATTER: undefined,
    RULES_DIR: '.codex/rules',
    RULES_SYNC_MANIFEST: undefined,
    SETTINGS_FILE: '.codex/settings.json',
    get SETTINGS_MANIFEST_KEY() {
      return this.AGENT_NAME;
    },
    SKILLS_SYNC_ENABLED: false,
  },
} as const satisfies AgentPresetConfig;
